<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed'); 

$modules = array(
	'eventcalendar' => 'Eventcalendar'
	);

$aliases = array(

	);

$disable_controller = array(

	);



/* End of file modules.php */
/* Auto generated by Themes Administration on : 2013.04.22 02:56:30 */
/* Location: /var/www/rebelsound/application//config/modules.php */
