<?php if ( ! defined('BASEPATH')){exit('Invalid file request');}

$views = array (
  'page' => 
  array (
    'page_blog' => 'Blog',
    'page_blog_post' => 'Blog Post',
    'page_contact' => 'Contact',
    'page_home' => 'Home',
    'page_my_account' => 'My Account',
    'page' => 'Page',
  ),
);


/* End of file views.php */
/* Auto generated by Themes Administration on : 2013.04.21 22:37:06 */
/* Location: /var/www/rebelsound/application/../themes/bootstrap/config/views.php */
